### ISSUE TITLE
gt_write_symbol:gdxError GDX error for DataOut: Duplicate keys

### ISSUE THREAD

**Issue by sebastianneu** [GAMS-dev/transfer-r#4]
Hi,

I am using R gamstransfer quite a time and now get a strange error when writing gdx. I prepare similar structured dataframes of data from countries to be exported as gdx. This once worked well. Then, I changed the structure of the data for all countries the same way, but now I get the above mentioned error for some countries, for some not. I tried to check for duplicate entries, there are no duplicates. But what does duplicate keys mean here?
Tracing back the error message, the following is shown:
3. .CPP_gdxWrite(self, enable, writeTo, uelPriority, compress, mode_int)
4. stop(structure(list(message = "gt_write_symbol:gdxError GDX error for DataOut: Duplicate keys",
call = NULL, cppstack = NULL), class = c("Rcpp::exception","C++Error", "error", "condition")))

Thanks in advance

**Comment by abhosekar** [comment]
The error is thrown from the GDX API so looks like your data passes the preliminary checks that `gamstransfer` performs.  It is difficult to say anything more without looking at your data and without knowing how you are writing your data to GDX. Can you share

- minimal R code that you use to write the GDX file that reproduces this error?
- `gamstransfer` version number you are using

Note that you are getting this error when writing the symbol `DataOut` so that's probably a good starting point. You should get this error when using
`m$write("fileout.gdx", symbols="DataOut")` where `m` is the name of the Container.

**Comment by sebastianneu** [comment]
Thanks for the quick answer. Interestingly, m.write("fileout.gdx", symbols="DataOut") did not work. The container m is available, but it gives the error that m.write cannot be found. 
I am using gamstransfer_3.0.4.
To make a reproducable example is complicated as the data I am using is confidential and it has more than 50k observations. Reproducability is further not so easy, as it works for some countries and others not. 
Can you give me some advise where to look at that problem once the container is built?
What does duplicate keys mean?

Edit: I took the data frame which is going to be the parameter and produced a colum in which each row is like a parameter definition of one value of a parameter in GAMS (like each row p_parameter('ddd','aaa','ccc')=12;. This column is exported as a csv file. I used it in a GAMS file to make a parameter and execute unload it. No problems occured.

Edit2: Even the error message occurs, a gdx file is written. Once I try to open it in GAMS IDE, the error messege "Error opening gdx file: ... Message: expected data marker (BOI) not found in GDX file."

**Comment by abhosekar** [comment]
- Duplicate records is when your domain columns entries are duplicate. For example, ("i1", "j1", 1) and ("i1","j1",2) are duplicate rows since they have identical domain keys ("i1","j1"). You can use the method [`findDuplicateRecords`](https://transfer-r.readthedocs.io/en/latest/api_reference/Symbols/Parameter.html#methods) to get rows that have duplicate records.
For example, if you have `DataOut` as your symbol object, you can do
`DataOut$findDuplicateRecords()` and you will get a view of the data frame with duplicate entries. This should ideally be empty. You can then choose to preprocess your data accordingly. You can also use gamstransfer function `dropDuplicateRecords` to automatically drop duplicate records.
- the method is `m$write` and not `m.write`. This is why you get the method not found error. Are you using this `$write` method in your code already or are you using something else? Your issue is unclear about it. 
- In the second edit, it makes sense that if an error is thrown the resulting GDX file is corrupt and you get an error. I wouldn't worry too much about it.

**Comment by sebastianneu** [comment]
WIth the help of an experienced GAMS modeler next to my office we used the dropDuplicateRecords() method. Even though I thought I provided a unique data set, it was not the case regarding the domains. [findDuplicateRecords](https://transfer-r.readthedocs.io/en/latest/api_reference/Symbols/Parameter.html#methods) (as you mentioned) showed me the duplicates. 

Lesson: unique data frames in R are not necessarily without duplicates for gamstransfer. It might be the case that applying unique() to your data frame does not work properly.

Thanks for your help.
